### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by pixene** [Saturate/traefik-wordpress#1]
Sorry but when I start docker-compose up -d ans i go to check web site adress, i got: Error establishing a database connection.

docker ps shows that traefik wp and databse are on.

Do u have any idea?

**Comment by Saturate** [comment]
Sounds strange, it works perfect for me.

Can you provide me with some more information? Like what OS you are using ect.

**Comment by Saturate** [comment]
Closing as there is no new information
